AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'log/**/*'
    - 'config/**/*'
Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 100
Style/ClassAndModuleChildren:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
