default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: shturming_development

test:
  <<: *default
  database: shturming_test

production:
  <<: *default
  database: shturming_production
