# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a3c1ce5d2810d80d38470f00bc29cee0dc82c23d2159fd3172f96d58168931cd6822865a35a4dcbfd177e54de70a4537e2c84da8fd65729cd3519531c8b5b4c

test:
  secret_key_base: cad1a020450a2efd099af2c029604d764292781b1632640e74b8054a09bd107fe6d12433dfbaac47fc00e60153998727527f1e7e10491af03ee386448e6056e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
